package cn.tushu.model;

import java.util.Date;

public class Adminuser {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column adminuser.adminuid
	 * @mbggenerated  Fri Jul 17 11:54:05 CST 2015
	 */
	private Integer adminuid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column adminuser.username
	 * @mbggenerated  Fri Jul 17 11:54:05 CST 2015
	 */
	private String username;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column adminuser.password
	 * @mbggenerated  Fri Jul 17 11:54:05 CST 2015
	 */
	private String password;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column adminuser.dender
	 * @mbggenerated  Fri Jul 17 11:54:05 CST 2015
	 */
	private Integer dender;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column adminuser.birthday
	 * @mbggenerated  Fri Jul 17 11:54:05 CST 2015
	 */
	private Date birthday;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column adminuser.registime
	 * @mbggenerated  Fri Jul 17 11:54:05 CST 2015
	 */
	private Date registime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column adminuser.state
	 * @mbggenerated  Fri Jul 17 11:54:05 CST 2015
	 */
	private Integer state;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column adminuser.adminuid
	 * @return  the value of adminuser.adminuid
	 * @mbggenerated  Fri Jul 17 11:54:05 CST 2015
	 */
	public Integer getAdminuid() {
		return adminuid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column adminuser.adminuid
	 * @param adminuid  the value for adminuser.adminuid
	 * @mbggenerated  Fri Jul 17 11:54:05 CST 2015
	 */
	public void setAdminuid(Integer adminuid) {
		this.adminuid = adminuid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column adminuser.username
	 * @return  the value of adminuser.username
	 * @mbggenerated  Fri Jul 17 11:54:05 CST 2015
	 */
	public String getUsername() {
		return username;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column adminuser.username
	 * @param username  the value for adminuser.username
	 * @mbggenerated  Fri Jul 17 11:54:05 CST 2015
	 */
	public void setUsername(String username) {
		this.username = username;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column adminuser.password
	 * @return  the value of adminuser.password
	 * @mbggenerated  Fri Jul 17 11:54:05 CST 2015
	 */
	public String getPassword() {
		return password;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column adminuser.password
	 * @param password  the value for adminuser.password
	 * @mbggenerated  Fri Jul 17 11:54:05 CST 2015
	 */
	public void setPassword(String password) {
		this.password = password;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column adminuser.dender
	 * @return  the value of adminuser.dender
	 * @mbggenerated  Fri Jul 17 11:54:05 CST 2015
	 */
	public Integer getDender() {
		return dender;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column adminuser.dender
	 * @param dender  the value for adminuser.dender
	 * @mbggenerated  Fri Jul 17 11:54:05 CST 2015
	 */
	public void setDender(Integer dender) {
		this.dender = dender;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column adminuser.birthday
	 * @return  the value of adminuser.birthday
	 * @mbggenerated  Fri Jul 17 11:54:05 CST 2015
	 */
	public Date getBirthday() {
		return birthday;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column adminuser.birthday
	 * @param birthday  the value for adminuser.birthday
	 * @mbggenerated  Fri Jul 17 11:54:05 CST 2015
	 */
	public void setBirthday(Date birthday) {
		this.birthday = birthday;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column adminuser.registime
	 * @return  the value of adminuser.registime
	 * @mbggenerated  Fri Jul 17 11:54:05 CST 2015
	 */
	public Date getRegistime() {
		return registime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column adminuser.registime
	 * @param registime  the value for adminuser.registime
	 * @mbggenerated  Fri Jul 17 11:54:05 CST 2015
	 */
	public void setRegistime(Date registime) {
		this.registime = registime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column adminuser.state
	 * @return  the value of adminuser.state
	 * @mbggenerated  Fri Jul 17 11:54:05 CST 2015
	 */
	public Integer getState() {
		return state;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column adminuser.state
	 * @param state  the value for adminuser.state
	 * @mbggenerated  Fri Jul 17 11:54:05 CST 2015
	 */
	public void setState(Integer state) {
		this.state = state;
	}
}