package cn.tushu.model;

public class AuRole {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column au_role.id
     *
     * @mbggenerated Fri Jul 17 11:55:25 CST 2015
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column au_role.adminuid
     *
     * @mbggenerated Fri Jul 17 11:55:25 CST 2015
     */
    private Integer adminuid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column au_role.rid
     *
     * @mbggenerated Fri Jul 17 11:55:25 CST 2015
     */
    private Integer rid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column au_role.id
     *
     * @return the value of au_role.id
     *
     * @mbggenerated Fri Jul 17 11:55:25 CST 2015
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column au_role.id
     *
     * @param id the value for au_role.id
     *
     * @mbggenerated Fri Jul 17 11:55:25 CST 2015
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column au_role.adminuid
     *
     * @return the value of au_role.adminuid
     *
     * @mbggenerated Fri Jul 17 11:55:25 CST 2015
     */
    public Integer getAdminuid() {
        return adminuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column au_role.adminuid
     *
     * @param adminuid the value for au_role.adminuid
     *
     * @mbggenerated Fri Jul 17 11:55:25 CST 2015
     */
    public void setAdminuid(Integer adminuid) {
        this.adminuid = adminuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column au_role.rid
     *
     * @return the value of au_role.rid
     *
     * @mbggenerated Fri Jul 17 11:55:25 CST 2015
     */
    public Integer getRid() {
        return rid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column au_role.rid
     *
     * @param rid the value for au_role.rid
     *
     * @mbggenerated Fri Jul 17 11:55:25 CST 2015
     */
    public void setRid(Integer rid) {
        this.rid = rid;
    }
}