package cn.tushu.model;

public class Book {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column book.bookId
	 * @mbggenerated  Wed Jun 10 17:03:17 CST 2015
	 */
	private Integer bookid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column book.bookname
	 * @mbggenerated  Wed Jun 10 17:03:17 CST 2015
	 */
	private String bookname;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column book.stock
	 * @mbggenerated  Wed Jun 10 17:03:17 CST 2015
	 */
	private Integer stock;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column book.author
	 * @mbggenerated  Wed Jun 10 17:03:17 CST 2015
	 */
	private String author;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column book.price
	 * @mbggenerated  Wed Jun 10 17:03:17 CST 2015
	 */
	private Integer price;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column book.imgSize
	 * @mbggenerated  Wed Jun 10 17:03:17 CST 2015
	 */
	private String imgsize;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column book.bookId
	 * @return  the value of book.bookId
	 * @mbggenerated  Wed Jun 10 17:03:17 CST 2015
	 */
	public Integer getBookid() {
		return bookid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column book.bookId
	 * @param bookid  the value for book.bookId
	 * @mbggenerated  Wed Jun 10 17:03:17 CST 2015
	 */
	public void setBookid(Integer bookid) {
		this.bookid = bookid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column book.bookname
	 * @return  the value of book.bookname
	 * @mbggenerated  Wed Jun 10 17:03:17 CST 2015
	 */
	public String getBookname() {
		return bookname;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column book.bookname
	 * @param bookname  the value for book.bookname
	 * @mbggenerated  Wed Jun 10 17:03:17 CST 2015
	 */
	public void setBookname(String bookname) {
		this.bookname = bookname;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column book.stock
	 * @return  the value of book.stock
	 * @mbggenerated  Wed Jun 10 17:03:17 CST 2015
	 */
	public Integer getStock() {
		return stock;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column book.stock
	 * @param stock  the value for book.stock
	 * @mbggenerated  Wed Jun 10 17:03:17 CST 2015
	 */
	public void setStock(Integer stock) {
		this.stock = stock;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column book.author
	 * @return  the value of book.author
	 * @mbggenerated  Wed Jun 10 17:03:17 CST 2015
	 */
	public String getAuthor() {
		return author;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column book.author
	 * @param author  the value for book.author
	 * @mbggenerated  Wed Jun 10 17:03:17 CST 2015
	 */
	public void setAuthor(String author) {
		this.author = author;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column book.price
	 * @return  the value of book.price
	 * @mbggenerated  Wed Jun 10 17:03:17 CST 2015
	 */
	public Integer getPrice() {
		return price;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column book.price
	 * @param price  the value for book.price
	 * @mbggenerated  Wed Jun 10 17:03:17 CST 2015
	 */
	public void setPrice(Integer price) {
		this.price = price;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column book.imgSize
	 * @return  the value of book.imgSize
	 * @mbggenerated  Wed Jun 10 17:03:17 CST 2015
	 */
	public String getImgsize() {
		return imgsize;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column book.imgSize
	 * @param imgsize  the value for book.imgSize
	 * @mbggenerated  Wed Jun 10 17:03:17 CST 2015
	 */
	public void setImgsize(String imgsize) {
		this.imgsize = imgsize;
	}
}