package cn.tushu.model;

import java.util.Date;

public class Colltrade {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column colltrade.collid
     *
     * @mbggenerated Mon Jun 15 20:04:58 CST 2015
     */
    private Integer collid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column colltrade.bookname
     *
     * @mbggenerated Mon Jun 15 20:04:58 CST 2015
     */
    private String bookname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column colltrade.author
     *
     * @mbggenerated Mon Jun 15 20:04:58 CST 2015
     */
    private String author;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column colltrade.price
     *
     * @mbggenerated Mon Jun 15 20:04:58 CST 2015
     */
    private Double price;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column colltrade.userid
     *
     * @mbggenerated Mon Jun 15 20:04:58 CST 2015
     */
    private Integer userid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column colltrade.cid
     *
     * @mbggenerated Mon Jun 15 20:04:58 CST 2015
     */
    private Integer cid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column colltrade.date
     *
     * @mbggenerated Mon Jun 15 20:04:58 CST 2015
     */
    private Date date;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column colltrade.imgsize
     *
     * @mbggenerated Mon Jun 15 20:04:58 CST 2015
     */
    private String imgsize;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column colltrade.collid
     *
     * @return the value of colltrade.collid
     *
     * @mbggenerated Mon Jun 15 20:04:58 CST 2015
     */
    public Integer getCollid() {
        return collid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column colltrade.collid
     *
     * @param collid the value for colltrade.collid
     *
     * @mbggenerated Mon Jun 15 20:04:58 CST 2015
     */
    public void setCollid(Integer collid) {
        this.collid = collid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column colltrade.bookname
     *
     * @return the value of colltrade.bookname
     *
     * @mbggenerated Mon Jun 15 20:04:58 CST 2015
     */
    public String getBookname() {
        return bookname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column colltrade.bookname
     *
     * @param bookname the value for colltrade.bookname
     *
     * @mbggenerated Mon Jun 15 20:04:58 CST 2015
     */
    public void setBookname(String bookname) {
        this.bookname = bookname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column colltrade.author
     *
     * @return the value of colltrade.author
     *
     * @mbggenerated Mon Jun 15 20:04:58 CST 2015
     */
    public String getAuthor() {
        return author;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column colltrade.author
     *
     * @param author the value for colltrade.author
     *
     * @mbggenerated Mon Jun 15 20:04:58 CST 2015
     */
    public void setAuthor(String author) {
        this.author = author;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column colltrade.price
     *
     * @return the value of colltrade.price
     *
     * @mbggenerated Mon Jun 15 20:04:58 CST 2015
     */
    public Double getPrice() {
        return price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column colltrade.price
     *
     * @param price the value for colltrade.price
     *
     * @mbggenerated Mon Jun 15 20:04:58 CST 2015
     */
    public void setPrice(Double price) {
        this.price = price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column colltrade.userid
     *
     * @return the value of colltrade.userid
     *
     * @mbggenerated Mon Jun 15 20:04:58 CST 2015
     */
    public Integer getUserid() {
        return userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column colltrade.userid
     *
     * @param userid the value for colltrade.userid
     *
     * @mbggenerated Mon Jun 15 20:04:58 CST 2015
     */
    public void setUserid(Integer userid) {
        this.userid = userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column colltrade.cid
     *
     * @return the value of colltrade.cid
     *
     * @mbggenerated Mon Jun 15 20:04:58 CST 2015
     */
    public Integer getCid() {
        return cid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column colltrade.cid
     *
     * @param cid the value for colltrade.cid
     *
     * @mbggenerated Mon Jun 15 20:04:58 CST 2015
     */
    public void setCid(Integer cid) {
        this.cid = cid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column colltrade.date
     *
     * @return the value of colltrade.date
     *
     * @mbggenerated Mon Jun 15 20:04:58 CST 2015
     */
    public Date getDate() {
        return date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column colltrade.date
     *
     * @param date the value for colltrade.date
     *
     * @mbggenerated Mon Jun 15 20:04:58 CST 2015
     */
    public void setDate(Date date) {
        this.date = date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column colltrade.imgsize
     *
     * @return the value of colltrade.imgsize
     *
     * @mbggenerated Mon Jun 15 20:04:58 CST 2015
     */
    public String getImgsize() {
        return imgsize;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column colltrade.imgsize
     *
     * @param imgsize the value for colltrade.imgsize
     *
     * @mbggenerated Mon Jun 15 20:04:58 CST 2015
     */
    public void setImgsize(String imgsize) {
        this.imgsize = imgsize;
    }
}