package cn.tushu.model;

public class Jurisdict {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jurisdict.jid
     *
     * @mbggenerated Wed Jul 22 10:41:46 CST 2015
     */
    private Integer jid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jurisdict.jname
     *
     * @mbggenerated Wed Jul 22 10:41:46 CST 2015
     */
    private String jname;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jurisdict.jid
     *
     * @return the value of jurisdict.jid
     *
     * @mbggenerated Wed Jul 22 10:41:46 CST 2015
     */
    public Integer getJid() {
        return jid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jurisdict.jid
     *
     * @param jid the value for jurisdict.jid
     *
     * @mbggenerated Wed Jul 22 10:41:46 CST 2015
     */
    public void setJid(Integer jid) {
        this.jid = jid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jurisdict.jname
     *
     * @return the value of jurisdict.jname
     *
     * @mbggenerated Wed Jul 22 10:41:46 CST 2015
     */
    public String getJname() {
        return jname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jurisdict.jname
     *
     * @param jname the value for jurisdict.jname
     *
     * @mbggenerated Wed Jul 22 10:41:46 CST 2015
     */
    public void setJname(String jname) {
        this.jname = jname;
    }
}