package cn.tushu.model;

public class RoleJuri {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column role_juri.id
     *
     * @mbggenerated Wed Jul 22 10:41:16 CST 2015
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column role_juri.rid
     *
     * @mbggenerated Wed Jul 22 10:41:16 CST 2015
     */
    private Integer rid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column role_juri.jid
     *
     * @mbggenerated Wed Jul 22 10:41:16 CST 2015
     */
    private Integer jid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column role_juri.fw_id
     *
     * @mbggenerated Wed Jul 22 10:41:16 CST 2015
     */
    private Integer fwId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column role_juri.id
     *
     * @return the value of role_juri.id
     *
     * @mbggenerated Wed Jul 22 10:41:16 CST 2015
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column role_juri.id
     *
     * @param id the value for role_juri.id
     *
     * @mbggenerated Wed Jul 22 10:41:16 CST 2015
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column role_juri.rid
     *
     * @return the value of role_juri.rid
     *
     * @mbggenerated Wed Jul 22 10:41:16 CST 2015
     */
    public Integer getRid() {
        return rid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column role_juri.rid
     *
     * @param rid the value for role_juri.rid
     *
     * @mbggenerated Wed Jul 22 10:41:16 CST 2015
     */
    public void setRid(Integer rid) {
        this.rid = rid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column role_juri.jid
     *
     * @return the value of role_juri.jid
     *
     * @mbggenerated Wed Jul 22 10:41:16 CST 2015
     */
    public Integer getJid() {
        return jid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column role_juri.jid
     *
     * @param jid the value for role_juri.jid
     *
     * @mbggenerated Wed Jul 22 10:41:16 CST 2015
     */
    public void setJid(Integer jid) {
        this.jid = jid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column role_juri.fw_id
     *
     * @return the value of role_juri.fw_id
     *
     * @mbggenerated Wed Jul 22 10:41:16 CST 2015
     */
    public Integer getFwId() {
        return fwId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column role_juri.fw_id
     *
     * @param fwId the value for role_juri.fw_id
     *
     * @mbggenerated Wed Jul 22 10:41:16 CST 2015
     */
    public void setFwId(Integer fwId) {
        this.fwId = fwId;
    }
}