package cn.tushu.model;

public class Share {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column share.shareId
     *
     * @mbggenerated Wed Jun 10 17:03:37 CST 2015
     */
    private Integer shareid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column share.userId
     *
     * @mbggenerated Wed Jun 10 17:03:37 CST 2015
     */
    private Integer userid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column share.bookName
     *
     * @mbggenerated Wed Jun 10 17:03:37 CST 2015
     */
    private String bookname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column share.author
     *
     * @mbggenerated Wed Jun 10 17:03:37 CST 2015
     */
    private String author;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column share.reason
     *
     * @mbggenerated Wed Jun 10 17:03:37 CST 2015
     */
    private String reason;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column share.imgSize
     *
     * @mbggenerated Wed Jun 10 17:03:37 CST 2015
     */
    private String imgsize;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column share.shareId
     *
     * @return the value of share.shareId
     *
     * @mbggenerated Wed Jun 10 17:03:37 CST 2015
     */
    public Integer getShareid() {
        return shareid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column share.shareId
     *
     * @param shareid the value for share.shareId
     *
     * @mbggenerated Wed Jun 10 17:03:37 CST 2015
     */
    public void setShareid(Integer shareid) {
        this.shareid = shareid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column share.userId
     *
     * @return the value of share.userId
     *
     * @mbggenerated Wed Jun 10 17:03:37 CST 2015
     */
    public Integer getUserid() {
        return userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column share.userId
     *
     * @param userid the value for share.userId
     *
     * @mbggenerated Wed Jun 10 17:03:37 CST 2015
     */
    public void setUserid(Integer userid) {
        this.userid = userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column share.bookName
     *
     * @return the value of share.bookName
     *
     * @mbggenerated Wed Jun 10 17:03:37 CST 2015
     */
    public String getBookname() {
        return bookname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column share.bookName
     *
     * @param bookname the value for share.bookName
     *
     * @mbggenerated Wed Jun 10 17:03:37 CST 2015
     */
    public void setBookname(String bookname) {
        this.bookname = bookname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column share.author
     *
     * @return the value of share.author
     *
     * @mbggenerated Wed Jun 10 17:03:37 CST 2015
     */
    public String getAuthor() {
        return author;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column share.author
     *
     * @param author the value for share.author
     *
     * @mbggenerated Wed Jun 10 17:03:37 CST 2015
     */
    public void setAuthor(String author) {
        this.author = author;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column share.reason
     *
     * @return the value of share.reason
     *
     * @mbggenerated Wed Jun 10 17:03:37 CST 2015
     */
    public String getReason() {
        return reason;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column share.reason
     *
     * @param reason the value for share.reason
     *
     * @mbggenerated Wed Jun 10 17:03:37 CST 2015
     */
    public void setReason(String reason) {
        this.reason = reason;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column share.imgSize
     *
     * @return the value of share.imgSize
     *
     * @mbggenerated Wed Jun 10 17:03:37 CST 2015
     */
    public String getImgsize() {
        return imgsize;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column share.imgSize
     *
     * @param imgsize the value for share.imgSize
     *
     * @mbggenerated Wed Jun 10 17:03:37 CST 2015
     */
    public void setImgsize(String imgsize) {
        this.imgsize = imgsize;
    }
}