package cn.tushu.model;

import java.util.Date;

public class Share {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column share.shareId
	 * @mbggenerated  Mon Jun 15 11:13:58 CST 2015
	 */
	private Integer shareid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column share.userId
	 * @mbggenerated  Mon Jun 15 11:13:58 CST 2015
	 */
	private Integer userid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column share.bookName
	 * @mbggenerated  Mon Jun 15 11:13:58 CST 2015
	 */
	private String bookname;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column share.author
	 * @mbggenerated  Mon Jun 15 11:13:58 CST 2015
	 */
	private String author;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column share.reason
	 * @mbggenerated  Mon Jun 15 11:13:58 CST 2015
	 */
	private String reason;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column share.imgSize
	 * @mbggenerated  Mon Jun 15 11:13:58 CST 2015
	 */
	private String imgsize;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column share.cid
	 * @mbggenerated  Mon Jun 15 11:13:58 CST 2015
	 */
	private Integer cid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column share.date
	 * @mbggenerated  Mon Jun 15 11:13:58 CST 2015
	 */
	private Date date;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column share.heat
	 * @mbggenerated  Mon Jun 15 11:13:58 CST 2015
	 */
	private Integer heat;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column share.shareId
	 * @return  the value of share.shareId
	 * @mbggenerated  Mon Jun 15 11:13:58 CST 2015
	 */
	public Integer getShareid() {
		return shareid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column share.shareId
	 * @param shareid  the value for share.shareId
	 * @mbggenerated  Mon Jun 15 11:13:58 CST 2015
	 */
	public void setShareid(Integer shareid) {
		this.shareid = shareid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column share.userId
	 * @return  the value of share.userId
	 * @mbggenerated  Mon Jun 15 11:13:58 CST 2015
	 */
	public Integer getUserid() {
		return userid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column share.userId
	 * @param userid  the value for share.userId
	 * @mbggenerated  Mon Jun 15 11:13:58 CST 2015
	 */
	public void setUserid(Integer userid) {
		this.userid = userid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column share.bookName
	 * @return  the value of share.bookName
	 * @mbggenerated  Mon Jun 15 11:13:58 CST 2015
	 */
	public String getBookname() {
		return bookname;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column share.bookName
	 * @param bookname  the value for share.bookName
	 * @mbggenerated  Mon Jun 15 11:13:58 CST 2015
	 */
	public void setBookname(String bookname) {
		this.bookname = bookname;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column share.author
	 * @return  the value of share.author
	 * @mbggenerated  Mon Jun 15 11:13:58 CST 2015
	 */
	public String getAuthor() {
		return author;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column share.author
	 * @param author  the value for share.author
	 * @mbggenerated  Mon Jun 15 11:13:58 CST 2015
	 */
	public void setAuthor(String author) {
		this.author = author;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column share.reason
	 * @return  the value of share.reason
	 * @mbggenerated  Mon Jun 15 11:13:58 CST 2015
	 */
	public String getReason() {
		return reason;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column share.reason
	 * @param reason  the value for share.reason
	 * @mbggenerated  Mon Jun 15 11:13:58 CST 2015
	 */
	public void setReason(String reason) {
		this.reason = reason;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column share.imgSize
	 * @return  the value of share.imgSize
	 * @mbggenerated  Mon Jun 15 11:13:58 CST 2015
	 */
	public String getImgsize() {
		return imgsize;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column share.imgSize
	 * @param imgsize  the value for share.imgSize
	 * @mbggenerated  Mon Jun 15 11:13:58 CST 2015
	 */
	public void setImgsize(String imgsize) {
		this.imgsize = imgsize;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column share.cid
	 * @return  the value of share.cid
	 * @mbggenerated  Mon Jun 15 11:13:58 CST 2015
	 */
	public Integer getCid() {
		return cid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column share.cid
	 * @param cid  the value for share.cid
	 * @mbggenerated  Mon Jun 15 11:13:58 CST 2015
	 */
	public void setCid(Integer cid) {
		this.cid = cid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column share.date
	 * @return  the value of share.date
	 * @mbggenerated  Mon Jun 15 11:13:58 CST 2015
	 */
	public Date getDate() {
		return date;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column share.date
	 * @param date  the value for share.date
	 * @mbggenerated  Mon Jun 15 11:13:58 CST 2015
	 */
	public void setDate(Date date) {
		this.date = date;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column share.heat
	 * @return  the value of share.heat
	 * @mbggenerated  Mon Jun 15 11:13:58 CST 2015
	 */
	public Integer getHeat() {
		return heat;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column share.heat
	 * @param heat  the value for share.heat
	 * @mbggenerated  Mon Jun 15 11:13:58 CST 2015
	 */
	public void setHeat(Integer heat) {
		this.heat = heat;
	}
}